### ISSUE TITLE
Tuning?

### ISSUE THREAD

**Issue by dangom** [dpapavas/fretboard-trainer#1]
Thanks for the cool project. Yet I'm not sure if I'm crazy, but is the guitar not tuned to EADGBE?

This is what I would expect:
<img width="383" alt="Screen Shot 2019-10-09 at 09 32 06" src="https://user-images.githubusercontent.com/7881842/66486081-7aa46200-ea99-11e9-94ce-b40c1bf6a90f.png">

Yet the following gives me a wrong answer (tried both Safari & Firefox):
<img width="912" alt="Screen Shot 2019-10-09 at 09 31 55" src="https://user-images.githubusercontent.com/7881842/66486093-7d06bc00-ea99-11e9-9ce1-c76716c729e2.png">

And the notes are always off from what I'd have expected, not only in this example.

**Comment by dpapavas** [comment]
Thanks for the very detailed report!

The tuning is supposed to be the standard EADGBE.  What I'm pretty sure the problem you're experiencing is due, is the fact that notes (and accidentals) are rendered using UTF-8 characters and though I was hoping that specifying their size in pixels would allow me to position them safely, it seems that their metrics differ with each font.  (You should also be seeing a treble clef, which you seem to be missing entirely.)  I'm having similar issues with Firefox on my tablet.  I'll either have to see if I can get proper metrics via JS, or else use pre-rendered image-based musical symbols.

I should have this fixed soon and will keep this issue open until then.

**Comment by dpapavas** [comment]
I've made changes to draw musical symbols manually, instead of relying on fonts.  Can you give it a try and see if the problem is still there?

**Comment by dangom** [comment]
Looks like it's fixed. Awesome! Thank you!!
